CFLAGS_BASE   = -O3 -fomit-frame-pointer
CFLAGS_ARM   = $(CFLAGS_BASE) -mcpu=native
CFLAGS_NATIVE = $(CFLAGS_BASE) -march=native

CXXFLAGS_BASE   = -O3 -fomit-frame-pointer -I"../../../libs/boost/include"
CXXFLAGS_ARM   = $(CXXFLAGS_BASE) -mcpu=native
CXXFLAGS_NATIVE = $(CXXFLAGS_BASE) -march=native

CFLAGS = $(shell echo 'void main(){}' | gcc $(CFLAGS_NATIVE) -E - 1>/dev/null 2>/dev/null && echo $(CFLAGS_NATIVE) || echo $(CFLAGS_ARM))
CXXFLAGS = $(shell echo 'void main(){}' | g++ $(CXXFLAGS_NATIVE) -E - 1>/dev/null 2>/dev/null && echo $(CXXFLAGS_NATIVE) || echo $(CXXFLAGS_ARM))
