<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<project basedir="." default="build" name="lintim-lineplanning-cost-restricting-frequencies">
    <include file="../../base.xml"/>
    <property name="build-dir" value="build" />
    <property name="doc-dir" value="docs" />
    <path id="lintim-lineplanning-cost.classpath">
        <pathelement location="."/>
        <pathelement location="${core-folder}/lintim-core.jar"/>
    </path>
    <!-- Clean -->
    <target name="clean">
        <delete>
            <fileset dir="." includes="**/*.class"/>
        </delete>
    </target>
    <target depends="clean" name="cleanall"/>
    <!-- Create necessary folders -->
    <target name="init">
        <mkdir dir="${build-dir}"/>
    </target>
    <target name="init-docs">
        <mkdir dir="${doc-dir}"/>
    </target>
    <!-- Build tasks -->
    <target depends="base-lintim.build-core,build-project" name="build"/>
    <target name="build-project" depends="build-with-xpress, build-with-gurobi, build-without-xpress-and-gurobi" />
    <target name="build-documentation" depends="init-docs">
        <echo message="Building documentation" />
        <javadoc sourcepath="." destdir="${doc-dir}"/>
    </target>
    <!-- Solver specific build targets, will only be used if the respective solvers are installed -->
    <target name="build-with-xpress" depends="init" if="${xpress.installed}">
        <echo>Xpress installed</echo>
        <javac destdir="${build-dir}" encoding="UTF-8">
            <src path="."/>
            <classpath refid="lintim-lineplanning-cost.classpath"/>
            <include name="net/lintim/algorithm/lineplanning/CostRestrictingFrequenciesXpress.java" />
        </javac>
    </target>
    <target name="build-with-gurobi" depends="init" if="${gurobi.installed}">
        <echo>Gurobi installed</echo>
        <javac destdir="${build-dir}" encoding="UTF-8">
            <src path="."/>
            <classpath refid="lintim-lineplanning-cost.classpath"/>
            <include name="net/lintim/algorithm/lineplanning/CostRestrictingFrequenciesGurobi.java" />
        </javac>
    </target>
    <!-- Either Xpress or Gurobi is necessary, fail if none is present -->
    <target name="build-without-xpress-and-gurobi">
        <javac destdir="${build-dir}" encoding="UTF-8">
            <src path="."/>
            <classpath refid="lintim-lineplanning-cost.classpath"/>
            <exclude name="net/lintim/algorithm/lineplanning/CostRestrictingFrequenciesGurobi.java" />
            <exclude name="net/lintim/algorithm/lineplanning/CostRestrictingFrequenciesXpress.java" />
        </javac>
    </target>

</project>
