<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<project basedir="." default="build" name="lintim-vehicle-scheduling-ip-model">
    <include file="../../base.xml"/>
    <property name="build-dir" value="build" />
    <property name="src-dir" value="src" />
    <property name="doc-dir" value="docs" />
    <path id="lintim-vehicle-scheduling-ip-model.classpath">
        <pathelement location="."/>
        <pathelement location="${core-folder}/lintim-core.jar"/>
    </path>
    <!-- Clean -->
    <target name="clean">
        <delete>
            <fileset dir="." includes="**/*.class"/>
        </delete>
    </target>
    <target depends="clean" name="cleanall"/>
    <!-- Create necessary folders -->
    <target name="init">
        <mkdir dir="${build-dir}"/>
    </target>
    <target name="init-docs">
        <mkdir dir="${doc-dir}"/>
    </target>
    <!-- Build tasks -->
    <target depends="base-lintim.build-core,build-project" name="build"/>
    <target name="build-project" depends="build-solver-independent,build-with-gurobi" />
    <target name="build-solver-independent" depends="init">
        <javac destdir="${build-dir}" encoding="UTF-8">
            <src path="${src-dir}"/>
            <classpath refid="lintim-vehicle-scheduling-ip-model.classpath"/>
            <exclude name="net/lintim/algorithm/vehiclescheduling/IPModelGurobi.java"/>
        </javac>
    </target>
    <!-- Solver specific build targets, will only be used if the respective solvers are installed -->
    <target name="build-with-gurobi" depends="init" if="${gurobi.installed}">
        <echo>Gurobi installed</echo>
        <javac srcdir="${src-dir}" destdir="${build-dir}" encoding="UTF-8">
            <classpath refid="lintim-vehicle-scheduling-ip-model.classpath"/>
            <include name="net/lintim/algorithm/vehiclescheduling/IPModelGurobi.java"/>
        </javac>
    </target>
    <target name="build-documentation" depends="init-docs">
        <echo message="Building documentation" />
        <javadoc sourcepath="." destdir="${doc-dir}"/>
    </target>


</project>
